/* ============================================================
   UVIE — GST122 (Communication in English II) Question Bank
   NOTE: Generated from general knowledge of GST122-style topics
   listed in the uploaded course outline (topic names only — no
   source PDFs/slides were provided). Cross-check against your
   actual course materials before relying on this for your exam.
   ============================================================ */

const QUESTIONS = [

/* ---------------- WEEK 1: Effective Communication ---------------- */
{ id:"w1-01", week:1, topic:"Effective Communication", difficulty:"easy",
  question:"What is the primary purpose of communication?",
  options:["To convey a message or meaning from a sender to a receiver","To fill silence in a conversation","To use correct grammar at all times","To speak as fast as possible"],
  correct:0,
  explanation:"Communication exists to transfer meaning from one party (the sender) to another (the receiver) so they arrive at a shared understanding.",
  memoryTip:"Think: Communication = Common + Understanding." },
{ id:"w1-02", week:1, topic:"Effective Communication", difficulty:"easy",
  question:"The communication process begins with which stage?",
  options:["Feedback","The sender encoding a message","Noise","Decoding"],
  correct:1,
  explanation:"Communication starts when the sender formulates an idea and encodes it into a message (words, symbols, etc.) to be sent.",
  memoryTip:"S.E.M.D.R.F — Sender, Encode, Message, Decode, Receiver, Feedback." },
{ id:"w1-03", week:1, topic:"Effective Communication", difficulty:"easy",
  question:"Which element of the communication process refers to anything that distorts or interferes with a message?",
  options:["Feedback","Channel","Noise","Context"],
  correct:2,
  explanation:"'Noise' is the general term for any interference — physical, psychological, or semantic — that disrupts accurate transmission of a message.",
  memoryTip:"Noise = anything 'noisy' that drowns out the real message." },
{ id:"w1-04", week:1, topic:"Effective Communication", difficulty:"easy",
  question:"'Feedback' in the communication process refers to:",
  options:["The original message sent","The medium used to send a message","The receiver's response to the sender's message","A grammatical error in a message"],
  correct:2,
  explanation:"Feedback is the receiver's reaction or response, which tells the sender whether the message was understood as intended.",
  memoryTip:"Feedback = the loop that closes the communication circle." },
{ id:"w1-05", week:1, topic:"Effective Communication", difficulty:"medium",
  question:"Which of these is NOT one of the basic elements of the communication process?",
  options:["Sender","Message","Grammar rule-book","Receiver"],
  correct:2,
  explanation:"The core elements are sender, message, channel, receiver, and feedback. A 'grammar rule-book' is not a formal element of the communication model.",
  memoryTip:"Elements of communication don't include a textbook — they include people and the message itself." },
{ id:"w1-06", week:1, topic:"Effective Communication", difficulty:"medium",
  question:"A communication channel is best described as:",
  options:["The emotional tone of a message","The medium through which a message travels (e.g. speech, writing, phone)","The receiver's interpretation of a message","A barrier that blocks communication"],
  correct:1,
  explanation:"The channel is the pathway or medium — spoken, written, digital — used to carry the message from sender to receiver.",
  memoryTip:"Channel = the 'road' the message travels on." },
{ id:"w1-07", week:1, topic:"Effective Communication", difficulty:"medium",
  question:"Effective communication requires clarity, which means:",
  options:["Using the longest words possible","The message is easily understood without ambiguity","The message is delivered as fast as possible","The sender never receives feedback"],
  correct:1,
  explanation:"Clarity means the message is expressed simply and precisely enough that the receiver can understand it without confusion.",
  memoryTip:"Clarity = clear + simplicity, not complexity." },
{ id:"w1-08", week:1, topic:"Effective Communication", difficulty:"medium",
  question:"A physical barrier to communication would be:",
  options:["Cultural misunderstanding","Background noise or distance between speakers","Ambiguous word choice","Emotional bias"],
  correct:1,
  explanation:"Physical/environmental barriers are tangible obstacles like noise, poor connections, or physical distance that interfere with a message reaching the receiver clearly.",
  memoryTip:"Physical barrier = something you could literally bump into or hear over." },
{ id:"w1-09", week:1, topic:"Effective Communication", difficulty:"medium",
  question:"A barrier arising from differing interpretations of words or cultural background is called a:",
  options:["Physical barrier","Semantic/cultural barrier","Channel barrier","Feedback barrier"],
  correct:1,
  explanation:"Semantic and cultural barriers occur when the sender and receiver assign different meanings to the same words or symbols due to language or cultural differences.",
  memoryTip:"Semantic = about the meaning of the 'semantics' (words)." },
{ id:"w1-10", week:1, topic:"Effective Communication", difficulty:"hard",
  question:"For communication to be considered effective, the receiver must:",
  options:["Simply hear the message","Correctly decode and understand the intended meaning","Repeat the message word-for-word","Ignore any noise present"],
  correct:1,
  explanation:"Effectiveness is measured by whether the receiver's understanding matches the sender's intended meaning — not just by whether sound reached their ears.",
  memoryTip:"Effective = the meaning survives the trip intact." },
{ id:"w1-11", week:1, topic:"Effective Communication", difficulty:"hard",
  question:"Non-verbal communication includes all of the following EXCEPT:",
  options:["Facial expressions","Body language and gestures","A written memo","Tone of voice (in face-to-face speech)"],
  correct:2,
  explanation:"A written memo is a form of verbal communication (it uses words), whereas facial expressions, gestures, and tone are non-verbal cues that accompany or replace words.",
  memoryTip:"Non-verbal = 'non-word' — body, face, tone, not text." },

/* ---------------- WEEK 1: Language Skills ---------------- */
{ id:"w1-12", week:1, topic:"Language Skills", difficulty:"easy",
  question:"The four basic language skills are:",
  options:["Reading, writing, spelling, grammar","Listening, speaking, reading, writing","Talking, texting, typing, singing","Vocabulary, phonetics, syntax, semantics"],
  correct:1,
  explanation:"The four core language skills taught and assessed are listening, speaking, reading, and writing.",
  memoryTip:"LSRW — Listen, Speak, Read, Write." },
{ id:"w1-13", week:1, topic:"Language Skills", difficulty:"easy",
  question:"Which language skills are classified as 'receptive' skills?",
  options:["Speaking and writing","Listening and reading","Speaking and listening","Writing and reading only"],
  correct:1,
  explanation:"Receptive skills involve receiving and interpreting input — listening and reading — as opposed to producing language.",
  memoryTip:"Receptive = you RECEIVE input: Listen & Read." },
{ id:"w1-14", week:1, topic:"Language Skills", difficulty:"easy",
  question:"Which language skills are classified as 'productive' skills?",
  options:["Listening and reading","Speaking and writing","Reading and writing","Listening and speaking"],
  correct:1,
  explanation:"Productive skills involve generating language output — speaking and writing — as opposed to interpreting input.",
  memoryTip:"Productive = you PRODUCE output: Speak & Write." },
{ id:"w1-15", week:1, topic:"Language Skills", difficulty:"medium",
  question:"Which language skill typically develops first in natural language acquisition?",
  options:["Writing","Reading","Listening","Speaking (before listening)"],
  correct:2,
  explanation:"Listening is usually the first skill developed, since infants and learners absorb sound and meaning before they can produce speech or read/write.",
  memoryTip:"Babies listen long before they talk." },
{ id:"w1-16", week:1, topic:"Language Skills", difficulty:"medium",
  question:"Active listening differs from simply 'hearing' because it involves:",
  options:["Focused attention and interpretation of meaning","Only physically detecting sound waves","Ignoring the speaker's tone","Reading the speaker's lips only"],
  correct:0,
  explanation:"Hearing is a passive physical process, while listening actively requires attention, interpretation, and often a response.",
  memoryTip:"Hearing is with the ears; listening is with the mind." },
{ id:"w1-17", week:1, topic:"Language Skills", difficulty:"medium",
  question:"A key requirement for effective writing as a productive skill is:",
  options:["Writing as many words as possible","Clarity and logical organization of ideas","Avoiding all punctuation","Copying another writer's exact words"],
  correct:1,
  explanation:"Effective writing depends on organizing ideas clearly and logically so the reader can follow and understand the message.",
  memoryTip:"Good writing = clear ideas in a clear order." },
{ id:"w1-18", week:1, topic:"Language Skills", difficulty:"hard",
  question:"Which of the four language skills is most commonly assessed through essays and reports?",
  options:["Listening","Speaking","Writing","Reading (only)"],
  correct:2,
  explanation:"Essays and reports are extended pieces of written output, making them a direct assessment of the productive skill of writing.",
  memoryTip:"Essays = evidence of Writing skill." },

/* ---------------- WEEK 2: Communication and Meaning ---------------- */
{ id:"w2-01", week:2, topic:"Communication and Meaning", difficulty:"easy",
  question:"Meaning in communication is commonly classified into which two types?",
  options:["Denotative and connotative","Verbal and grammatical","Formal and informal","Written and spoken"],
  correct:0,
  explanation:"Words carry denotative meaning (literal/dictionary sense) and connotative meaning (implied, emotional, or cultural association).",
  memoryTip:"Denotative = Dictionary. Connotative = Cultural/emotional Connection." },
{ id:"w2-02", week:2, topic:"Communication and Meaning", difficulty:"easy",
  question:"Denotative meaning refers to:",
  options:["The emotional association of a word","The literal, dictionary definition of a word","Slang usage of a word","A word's meaning in a specific culture only"],
  correct:1,
  explanation:"Denotation is a word's exact, literal, dictionary-defined meaning, free of emotional or cultural coloring.",
  memoryTip:"Denotative = 'De-notes' the literal fact." },
{ id:"w2-03", week:2, topic:"Communication and Meaning", difficulty:"easy",
  question:"Connotative meaning refers to:",
  options:["A word's spelling variations","The implied or emotional association attached to a word","A word's part of speech","The number of syllables in a word"],
  correct:1,
  explanation:"Connotation is the emotional or cultural association a word carries beyond its literal definition.",
  memoryTip:"Connotative = the feeling that 'CONnects' to the word." },
{ id:"w2-04", week:2, topic:"Communication and Meaning", difficulty:"medium",
  question:"Which example best illustrates connotative meaning?",
  options:["'Water' means H2O","Calling someone 'stubborn' instead of 'determined' for the same trait","'Cat' is a four-letter word","'Run' can be used as a noun or verb"],
  correct:1,
  explanation:"'Stubborn' and 'determined' can describe the same behavior but carry very different emotional connotations — negative vs. positive.",
  memoryTip:"Same fact, different feeling = connotation at work." },
{ id:"w2-05", week:2, topic:"Communication and Meaning", difficulty:"medium",
  question:"Why does context matter in communication?",
  options:["It has no real effect on meaning","It helps determine the intended meaning of an otherwise ambiguous message","It only matters in written communication","It replaces the need for grammar"],
  correct:1,
  explanation:"The same words can mean different things depending on situational, cultural, or conversational context, so context helps resolve ambiguity.",
  memoryTip:"Context is king — it decides which meaning wins." },
{ id:"w2-06", week:2, topic:"Communication and Meaning", difficulty:"medium",
  question:"Ambiguity in communication occurs when:",
  options:["A message is very short","A message can be interpreted in more than one way","A message uses only simple words","The sender uses correct grammar"],
  correct:1,
  explanation:"Ambiguity arises when wording allows for multiple plausible interpretations, which can lead to miscommunication.",
  memoryTip:"Ambiguous = 'AMBI' (both/two) possible meanings." },
{ id:"w2-07", week:2, topic:"Communication and Meaning", difficulty:"hard",
  question:"Semantics is best defined as the study of:",
  options:["Sentence punctuation","Meaning in language","Speech sounds only","Handwriting style"],
  correct:1,
  explanation:"Semantics is the branch of linguistics concerned with meaning — how words, phrases, and sentences convey meaning.",
  memoryTip:"SEMantics = the study of SEMantic meaning." },
{ id:"w2-08", week:2, topic:"Communication and Meaning", difficulty:"hard",
  question:"Pragmatics differs from semantics mainly because pragmatics focuses on:",
  options:["Meaning in context and actual language use","Only the dictionary meaning of words","Spelling rules","Sentence length"],
  correct:0,
  explanation:"While semantics studies literal meaning, pragmatics studies how meaning is shaped by context, speaker intention, and situation.",
  memoryTip:"PRAGmatics = PRACTICAL, real-world use of language." },
{ id:"w2-09", week:2, topic:"Communication and Meaning", difficulty:"hard",
  question:"Miscommunication most often arises from:",
  options:["Too much feedback","A mismatch between intended and interpreted meaning","Using too few words","Speaking too slowly"],
  correct:1,
  explanation:"Miscommunication happens when what the sender meant differs from what the receiver understood — a breakdown in shared meaning.",
  memoryTip:"Miscommunication = a meaning mismatch." },

/* ---------------- WEEK 2: Parts of Speech ---------------- */
{ id:"w2-10", week:2, topic:"Parts of Speech", difficulty:"easy",
  question:"How many major parts of speech are traditionally recognized in English?",
  options:["Five","Eight","Ten","Six"],
  correct:1,
  explanation:"The eight traditional parts of speech are noun, pronoun, verb, adjective, adverb, preposition, conjunction, and interjection.",
  memoryTip:"8 Parts of Speech: N-P-V-A-A-P-C-I." },
{ id:"w2-11", week:2, topic:"Parts of Speech", difficulty:"easy",
  question:"A noun is a word that:",
  options:["Shows an action","Names a person, place, thing, or idea","Describes a verb","Joins two clauses"],
  correct:1,
  explanation:"A noun names people, places, things, or abstract ideas (e.g. 'teacher', 'Lagos', 'book', 'freedom').",
  memoryTip:"Noun = Naming word." },
{ id:"w2-12", week:2, topic:"Parts of Speech", difficulty:"easy",
  question:"A verb primarily expresses:",
  options:["A description of a noun","An action or a state of being","A relationship between two nouns","An exclamation"],
  correct:1,
  explanation:"Verbs express actions (run, write) or states of being (is, seem, become).",
  memoryTip:"Verb = the word that 'moves' the sentence." },
{ id:"w2-13", week:2, topic:"Parts of Speech", difficulty:"easy",
  question:"An adjective's main function is to:",
  options:["Modify or describe a noun","Replace a noun","Join two sentences","Show location"],
  correct:0,
  explanation:"Adjectives describe or modify nouns and pronouns, adding detail like size, color, or quality.",
  memoryTip:"Adjective = 'ADDS' detail to a noun." },
{ id:"w2-14", week:2, topic:"Parts of Speech", difficulty:"medium",
  question:"An adverb typically modifies:",
  options:["Only nouns","A verb, adjective, or another adverb","Only prepositions","Only conjunctions"],
  correct:1,
  explanation:"Adverbs modify verbs (ran quickly), adjectives (very tall), or other adverbs (extremely well).",
  memoryTip:"Many adverbs end in -LY and answer 'how, when, where'." },
{ id:"w2-15", week:2, topic:"Parts of Speech", difficulty:"medium",
  question:"A pronoun's main function is to:",
  options:["Replace a noun","Describe an adjective","Show tense","Join independent clauses only"],
  correct:0,
  explanation:"Pronouns (he, she, it, they) stand in for nouns to avoid repetition.",
  memoryTip:"Pro-noun = 'FOR' a noun, standing in its place." },
{ id:"w2-16", week:2, topic:"Parts of Speech", difficulty:"medium",
  question:"A preposition shows:",
  options:["A sudden emotion","The relationship between a noun/pronoun and other words in a sentence","An action being performed","A comparison between two adjectives"],
  correct:1,
  explanation:"Prepositions (in, on, at, under, between) show relationships like place, time, or direction.",
  memoryTip:"Prepositions often show POSITION: in, on, under, over." },
{ id:"w2-17", week:2, topic:"Parts of Speech", difficulty:"medium",
  question:"A conjunction is used to:",
  options:["Express strong emotion","Join words, phrases, or clauses","Name a person or place","Replace a repeated noun"],
  correct:1,
  explanation:"Conjunctions (and, but, or, because) connect words, phrases, or clauses within a sentence.",
  memoryTip:"Conjunction = 'CONNECTS' ideas together." },
{ id:"w2-18", week:2, topic:"Parts of Speech", difficulty:"hard",
  question:"An interjection is used to express:",
  options:["A grammatical relationship","Sudden emotion or exclamation","The subject of a sentence","A logical conclusion"],
  correct:1,
  explanation:"Interjections (Wow!, Ouch!, Alas!) express sudden feeling and often stand independently, punctuated with an exclamation mark.",
  memoryTip:"Interjection = a word that 'jumps in' with emotion." },
{ id:"w2-19", week:2, topic:"Parts of Speech", difficulty:"hard",
  question:"In the sentence 'She quickly closed the door,' which word is the adverb?",
  options:["She","Quickly","Closed","Door"],
  correct:1,
  explanation:"'Quickly' modifies the verb 'closed,' describing how the action was performed — the defining function of an adverb.",
  memoryTip:"Ask 'HOW did she close it?' → Quickly = adverb." },

/* ---------------- WEEK 3: Concord ---------------- */
{ id:"w3-01", week:3, topic:"Concord", difficulty:"easy",
  question:"Concord (agreement) in grammar refers to:",
  options:["The correspondence between subject and verb in number and person","The use of correct punctuation","The order of adjectives in a sentence","The formation of new words"],
  correct:0,
  explanation:"Concord, or subject-verb agreement, requires that a verb's form (singular/plural) matches its subject.",
  memoryTip:"Concord = subject and verb must 'agree' / be in concord." },
{ id:"w3-02", week:3, topic:"Concord", difficulty:"medium",
  question:"Grammatical concord means:",
  options:["The verb agrees with the grammatical (surface) form of the subject","The verb agrees with the nearest noun regardless of the subject","The verb always stays singular","The subject changes to match the verb"],
  correct:0,
  explanation:"Grammatical concord is the standard rule: a singular subject takes a singular verb, and a plural subject takes a plural verb, based on form.",
  memoryTip:"Grammatical concord = follow the FORM (singular/plural) strictly." },
{ id:"w3-03", week:3, topic:"Concord", difficulty:"medium",
  question:"Notional concord means the verb agrees with:",
  options:["The perceived sense/meaning of the subject rather than its strict grammatical form","Only the first word of the sentence","The object of the sentence","The tense of the previous sentence"],
  correct:0,
  explanation:"Notional concord allows a collective noun to take a verb form that reflects its meaning (e.g. as a group of individuals vs. a single unit), even if that contradicts strict grammatical form.",
  memoryTip:"Notional = based on the NOTION (idea/sense), not just the form." },
{ id:"w3-04", week:3, topic:"Concord", difficulty:"medium",
  question:"Proximity concord means the verb agrees with:",
  options:["The subject furthest from the verb","The noun or pronoun closest to the verb","The object of the sentence","The main clause only"],
  correct:1,
  explanation:"Proximity (or 'attraction') concord occurs when the verb agrees with whichever noun is nearest to it, common in 'neither...nor' or 'either...or' constructions.",
  memoryTip:"Proximity = 'closest neighbor' wins the agreement." },
{ id:"w3-05", week:3, topic:"Concord", difficulty:"hard",
  question:"'The committee has decided on the new policy' demonstrates which type of concord?",
  options:["Notional concord","Grammatical concord (committee treated as one unit)","Proximity concord","No concord is present"],
  correct:1,
  explanation:"Here 'committee' is treated as a single, unified body, so it takes the singular verb 'has' — grammatical concord.",
  memoryTip:"One committee, one voice → singular verb." },
{ id:"w3-06", week:3, topic:"Concord", difficulty:"hard",
  question:"'The committee have different opinions on the matter' demonstrates which type of concord?",
  options:["Grammatical concord","Notional concord (committee treated as individuals)","Proximity concord","Reflexive concord"],
  correct:1,
  explanation:"Here 'committee' is understood as multiple individual members with differing views, so the plural verb 'have' reflects notional concord.",
  memoryTip:"Different opinions → thinking of them as separate people → plural verb." },
{ id:"w3-07", week:3, topic:"Concord", difficulty:"hard",
  question:"'Neither the teacher nor the students were present' illustrates:",
  options:["Grammatical concord only","Proximity concord — the verb agrees with 'students', the nearer subject","Notional concord","A punctuation rule, not concord"],
  correct:1,
  explanation:"In 'neither...nor' constructions, the verb typically agrees with the subject closest to it — here, 'students' (plural), giving 'were'.",
  memoryTip:"Neither/nor, either/or → verb matches the NEARER subject." },
{ id:"w3-08", week:3, topic:"Concord", difficulty:"medium",
  question:"Collective nouns like 'team', 'family', and 'government' can take:",
  options:["Only singular verbs, always","Only plural verbs, always","Singular or plural verbs depending on whether they're viewed as a unit or as individuals","No verb at all"],
  correct:2,
  explanation:"Collective nouns are flexible: singular verb when treated as one unit, plural verb when the members are considered as individuals.",
  memoryTip:"Collective nouns can 'switch teams' between singular and plural." },
{ id:"w3-09", week:3, topic:"Concord", difficulty:"hard",
  question:"'Each of the students has submitted their assignment.' Why is 'has' correct here?",
  options:["'Each' is a plural pronoun","'Each' is a singular indefinite pronoun, so it takes a singular verb","'Students' is closer to the verb","There is no rule governing this"],
  correct:1,
  explanation:"'Each', 'every', 'either', and 'neither' are grammatically singular indefinite pronouns and require a singular verb, regardless of what follows.",
  memoryTip:"EACH is always treated as ONE — singular verb." },

/* ---------------- WEEK 3: Sentence Structure & Word Classes ---------------- */
{ id:"w3-10", week:3, topic:"Sentence Structure & Word Classes", difficulty:"easy",
  question:"A simple sentence contains:",
  options:["Two independent clauses","One independent clause","One dependent clause only","No verb"],
  correct:1,
  explanation:"A simple sentence has exactly one independent clause with a subject and a predicate, expressing one complete thought.",
  memoryTip:"Simple sentence = simply ONE clause." },
{ id:"w3-11", week:3, topic:"Sentence Structure & Word Classes", difficulty:"medium",
  question:"A compound sentence contains:",
  options:["One independent clause only","Two or more independent clauses joined by a coordinating conjunction","An independent clause and a dependent clause","No conjunctions at all"],
  correct:1,
  explanation:"Compound sentences link two or more independent clauses using coordinating conjunctions (and, but, or, so, etc.) or a semicolon.",
  memoryTip:"Compound = COMBINE two full sentences with 'and/but/or'." },
{ id:"w3-12", week:3, topic:"Sentence Structure & Word Classes", difficulty:"medium",
  question:"A complex sentence contains:",
  options:["Two independent clauses only","An independent clause and at least one dependent clause","Only dependent clauses","No subject"],
  correct:1,
  explanation:"Complex sentences combine one independent clause with one or more dependent (subordinate) clauses, often joined by words like 'because', 'although', or 'when'.",
  memoryTip:"Complex = one clause can't stand alone (dependent) leaning on the main one." },
{ id:"w3-13", week:3, topic:"Sentence Structure & Word Classes", difficulty:"medium",
  question:"Function words in English include:",
  options:["Nouns, main verbs, and adjectives","Prepositions, conjunctions, pronouns, and articles","Only proper nouns","Interjections only"],
  correct:1,
  explanation:"Function words carry grammatical relationships rather than rich lexical meaning — they include prepositions, conjunctions, articles, and pronouns.",
  memoryTip:"Function words = the 'grammar glue' words." },
{ id:"w3-14", week:3, topic:"Sentence Structure & Word Classes", difficulty:"medium",
  question:"Content words in English include:",
  options:["Articles and prepositions","Nouns, main verbs, adjectives, and adverbs","Only conjunctions","Only pronouns"],
  correct:1,
  explanation:"Content words carry the main lexical/semantic meaning of a sentence — nouns, verbs, adjectives, and adverbs.",
  memoryTip:"Content words = the 'meat' of meaning in a sentence." },
{ id:"w3-15", week:3, topic:"Sentence Structure & Word Classes", difficulty:"hard",
  question:"Content words are considered an 'open class' because:",
  options:["They never change","New words can be freely added to the category over time","They are always short","They cannot be modified"],
  correct:1,
  explanation:"Open classes like nouns and verbs readily accept new coinages (e.g. 'google' as a verb), unlike closed classes such as prepositions and conjunctions.",
  memoryTip:"Open class = the 'door is open' for new words to join." },
{ id:"w3-16", week:3, topic:"Sentence Structure & Word Classes", difficulty:"easy",
  question:"Which of these is a function word?",
  options:["Beautiful","Run","The","Elephant"],
  correct:2,
  explanation:"'The' is an article, a function word that signals grammatical structure rather than carrying independent lexical meaning.",
  memoryTip:"Articles (a, an, the) are classic function words." },
{ id:"w3-17", week:3, topic:"Sentence Structure & Word Classes", difficulty:"medium",
  question:"A sentence's predicate is:",
  options:["The subject of the sentence","The part that says something about the subject (usually containing the verb)","Only the object","A punctuation mark"],
  correct:1,
  explanation:"The predicate is everything in the sentence that tells us what the subject does or is, typically built around the main verb.",
  memoryTip:"Predicate PREDICTS what the subject does." },

/* ---------------- WEEK 4: Punctuation ---------------- */
{ id:"w4-01", week:4, topic:"Punctuation", difficulty:"easy",
  question:"A comma is primarily used to:",
  options:["End a sentence","Separate items, clauses, or ideas within a sentence","Show possession","Introduce a formal quotation only"],
  correct:1,
  explanation:"Commas separate list items, clauses, or introductory elements to make a sentence easier to read and understand.",
  memoryTip:"Comma = a short PAUSE inside a sentence." },
{ id:"w4-02", week:4, topic:"Punctuation", difficulty:"medium",
  question:"A semicolon is typically used to:",
  options:["End a question","Join two closely related independent clauses without a conjunction","Show possession","Introduce a list only"],
  correct:1,
  explanation:"A semicolon links two independent clauses that are closely related in meaning, without needing a coordinating conjunction.",
  memoryTip:"Semicolon = a comma + period blended, joining two full ideas." },
{ id:"w4-03", week:4, topic:"Punctuation", difficulty:"medium",
  question:"A colon is typically used to:",
  options:["Show a pause mid-clause","Introduce a list, explanation, or quotation","Indicate a contraction","Mark the end of a paragraph"],
  correct:1,
  explanation:"A colon signals that what follows will explain, list, or elaborate on what came before it.",
  memoryTip:"Colon = 'here comes more detail:'" },
{ id:"w4-04", week:4, topic:"Punctuation", difficulty:"easy",
  question:"An apostrophe is used to show:",
  options:["A question","Possession or a contraction","The end of a sentence","A list of items"],
  correct:1,
  explanation:"Apostrophes mark possession ('Mary's book') or omitted letters in contractions ('don't' = do not).",
  memoryTip:"Apostrophe = 'it belongs to' OR 'letters are missing'." },
{ id:"w4-05", week:4, topic:"Punctuation", difficulty:"easy",
  question:"Quotation marks are used to:",
  options:["Show possession","Indicate direct speech or quoted material","Separate list items","End a declarative sentence"],
  correct:1,
  explanation:"Quotation marks enclose someone's exact spoken or written words when quoted directly.",
  memoryTip:"Quotation marks 'wrap around' exact words spoken/written." },
{ id:"w4-06", week:4, topic:"Punctuation", difficulty:"easy",
  question:"A full stop (period) is used to:",
  options:["Mark the end of a declarative sentence","Join two clauses","Show emphasis","Introduce a quotation"],
  correct:0,
  explanation:"The full stop marks the end of a complete declarative (statement) sentence.",
  memoryTip:"Full stop = full STOP, sentence complete." },
{ id:"w4-07", week:4, topic:"Punctuation", difficulty:"medium",
  question:"Which mark commonly joins independent clauses along with a coordinating conjunction like 'and', 'but', or 'or'?",
  options:["Semicolon","Comma","Colon","Apostrophe"],
  correct:1,
  explanation:"A comma before a coordinating conjunction (and, but, or, so, etc.) is the standard way to join two independent clauses.",
  memoryTip:"Comma + FANBOYS (for, and, nor, but, or, yet, so) joins clauses." },
{ id:"w4-08", week:4, topic:"Punctuation", difficulty:"hard",
  question:"The Oxford (serial) comma is used:",
  options:["Only in formal legal writing","Before the final 'and'/'or' in a list of three or more items","At the start of every sentence","To replace a full stop"],
  correct:1,
  explanation:"The Oxford comma is the optional comma placed before the final conjunction in a list, e.g. 'apples, oranges, and bananas'.",
  memoryTip:"Oxford comma = the comma right before the LAST 'and'." },
{ id:"w4-09", week:4, topic:"Punctuation", difficulty:"hard",
  question:"Joining two independent clauses with only a comma (no conjunction) is called:",
  options:["A correct compound sentence","A comma splice (a punctuation error)","A colon fault","An acceptable style choice always"],
  correct:1,
  explanation:"A comma splice is a common error where two complete sentences are incorrectly joined by just a comma; it should use a conjunction, semicolon, or be split into two sentences.",
  memoryTip:"Comma splice = comma trying to do a semicolon's job." },
{ id:"w4-10", week:4, topic:"Punctuation", difficulty:"medium",
  question:"Which punctuation mark is used to indicate an abrupt break or interruption in a sentence?",
  options:["Comma","Dash","Apostrophe","Full stop"],
  correct:1,
  explanation:"A dash (—) signals a sudden break, interruption, or emphatic aside within a sentence.",
  memoryTip:"Dash = a sudden 'dash' away from the main thought." },

/* ---------------- WEEK 4: Paragraphs & Topic Sentences ---------------- */
{ id:"w4-11", week:4, topic:"Paragraphs & Topic Sentences", difficulty:"easy",
  question:"A topic sentence:",
  options:["States the main idea of a paragraph","Is always the last sentence","Contains no verb","Only appears in essays, not paragraphs"],
  correct:0,
  explanation:"The topic sentence expresses the central idea that the rest of the paragraph will develop and support.",
  memoryTip:"Topic sentence = the paragraph's headline." },
{ id:"w4-12", week:4, topic:"Paragraphs & Topic Sentences", difficulty:"easy",
  question:"Where is a topic sentence most commonly placed in a paragraph?",
  options:["In the middle","At the beginning","At the very end only","It is never written explicitly"],
  correct:1,
  explanation:"While it can appear elsewhere, the topic sentence is most commonly placed at the start of a paragraph to orient the reader.",
  memoryTip:"Start strong — topic sentence usually leads." },
{ id:"w4-13", week:4, topic:"Paragraphs & Topic Sentences", difficulty:"medium",
  question:"Supporting sentences in a paragraph function to:",
  options:["Contradict the topic sentence","Provide details, evidence, or examples for the topic sentence","Replace the topic sentence","Introduce a completely new topic"],
  correct:1,
  explanation:"Supporting sentences develop and substantiate the main idea stated in the topic sentence with evidence, examples, or explanation.",
  memoryTip:"Supporting sentences = the 'proof' behind the main claim." },
{ id:"w4-14", week:4, topic:"Paragraphs & Topic Sentences", difficulty:"medium",
  question:"Paragraph unity means:",
  options:["Every sentence relates to a single main idea","The paragraph has exactly five sentences","All sentences are the same length","The paragraph avoids using pronouns"],
  correct:0,
  explanation:"Unity requires that every sentence in a paragraph contributes to and stays focused on the one main idea.",
  memoryTip:"Unity = UNIFIED around one idea, no off-topic wandering." },
{ id:"w4-15", week:4, topic:"Paragraphs & Topic Sentences", difficulty:"medium",
  question:"Paragraph coherence refers to:",
  options:["Logical flow and connection between sentences","Correct spelling only","The number of paragraphs in an essay","Using only short sentences"],
  correct:0,
  explanation:"Coherence is about how smoothly and logically ideas connect and flow from one sentence to the next.",
  memoryTip:"Coherence = ideas that 'stick together' logically." },
{ id:"w4-16", week:4, topic:"Paragraphs & Topic Sentences", difficulty:"hard",
  question:"Transitional words and phrases primarily help a paragraph achieve:",
  options:["Length","Coherence","A larger vocabulary count","Unrelated variety"],
  correct:1,
  explanation:"Transitions (however, therefore, in addition) signal the logical relationship between ideas, strengthening coherence.",
  memoryTip:"Transitions = the 'bridges' between ideas." },
{ id:"w4-17", week:4, topic:"Paragraphs & Topic Sentences", difficulty:"hard",
  question:"A paragraph lacking unity typically:",
  options:["Has too many transitions","Includes irrelevant or off-topic sentences","Has a topic sentence at the start","Uses correct punctuation throughout"],
  correct:1,
  explanation:"When a paragraph strays from its main idea with unrelated sentences, it loses unity.",
  memoryTip:"No unity = sentences wandering off-topic." },
{ id:"w4-18", week:4, topic:"Paragraphs & Topic Sentences", difficulty:"medium",
  question:"The purpose of a topic sentence is primarily to:",
  options:["Guide the reader on what the paragraph will discuss","End the paragraph decisively","List every supporting detail","Replace the need for a conclusion"],
  correct:0,
  explanation:"The topic sentence sets reader expectations by previewing the paragraph's focus.",
  memoryTip:"Topic sentence = a signpost for what's coming." },

/* ---------------- WEEK 5: Pre-writing & Post-writing ---------------- */
{ id:"w5-01", week:5, topic:"Pre-writing & Post-writing", difficulty:"easy",
  question:"Pre-writing refers to:",
  options:["The final proofreading stage","Activities done before drafting, such as brainstorming and outlining","Publishing the finished work","Grading a piece of writing"],
  correct:1,
  explanation:"Pre-writing is the planning phase where writers generate and organize ideas before producing a full draft.",
  memoryTip:"PRE-writing happens BEFORE the actual writing." },
{ id:"w5-02", week:5, topic:"Pre-writing & Post-writing", difficulty:"easy",
  question:"Which of these is an example of a pre-writing activity?",
  options:["Proofreading for spelling errors","Brainstorming, freewriting, or outlining","Publishing the final draft","Formatting the reference list"],
  correct:1,
  explanation:"Brainstorming, freewriting, clustering, and outlining are all common pre-writing techniques used to generate and organize ideas.",
  memoryTip:"Pre-writing = idea generation tools: brainstorm, outline, freewrite." },
{ id:"w5-03", week:5, topic:"Pre-writing & Post-writing", difficulty:"medium",
  question:"Post-writing activities include:",
  options:["Brainstorming and outlining","Revising, editing, and proofreading","Choosing a topic","Drafting the first version"],
  correct:1,
  explanation:"Post-writing covers everything done after a draft exists: revising for content, editing for grammar, and proofreading for errors.",
  memoryTip:"POST-writing happens AFTER the draft is written." },
{ id:"w5-04", week:5, topic:"Pre-writing & Post-writing", difficulty:"medium",
  question:"Revising a piece of writing primarily focuses on:",
  options:["Correcting comma placement only","Improving content, organization, and clarity","Choosing a font","Counting words"],
  correct:1,
  explanation:"Revision is 'big-picture' work — reworking ideas, structure, and clarity — before fine-tuning grammar.",
  memoryTip:"Revise = literally 'RE-VISION' — see the content again." },
{ id:"w5-05", week:5, topic:"Pre-writing & Post-writing", difficulty:"medium",
  question:"Editing a piece of writing primarily focuses on:",
  options:["Generating new ideas","Correcting grammar, spelling, and punctuation errors","Choosing the topic","Brainstorming an outline"],
  correct:1,
  explanation:"Editing is a finer-grained pass focused on correctness — grammar, spelling, punctuation — rather than content or structure.",
  memoryTip:"Editing = EDIT the errors, not the ideas." },
{ id:"w5-06", week:5, topic:"Pre-writing & Post-writing", difficulty:"medium",
  question:"Proofreading is best done:",
  options:["Before drafting begins","As the very first step","As the final step, after revising and editing","Instead of revising"],
  correct:2,
  explanation:"Proofreading is the last quality check for surface errors, done only after content (revising) and correctness (editing) have been addressed.",
  memoryTip:"Proofread LAST — the final polish before submission." },
{ id:"w5-07", week:5, topic:"Pre-writing & Post-writing", difficulty:"hard",
  question:"Outlining during pre-writing primarily helps writers:",
  options:["Avoid writing a draft entirely","Organize ideas logically before drafting","Correct spelling errors","Format citations"],
  correct:1,
  explanation:"An outline maps out the structure and order of ideas in advance, making the drafting process smoother and more organized.",
  memoryTip:"Outline = the 'skeleton' built before the essay's 'body'." },
{ id:"w5-08", week:5, topic:"Pre-writing & Post-writing", difficulty:"medium",
  question:"The drafting stage of the writing process comes:",
  options:["Before pre-writing","After pre-writing and before revising","After the final proofread","It doesn't exist as a stage"],
  correct:1,
  explanation:"Drafting is the middle stage: ideas gathered during pre-writing are turned into a first full version, which is then revised.",
  memoryTip:"Order: Pre-write → Draft → Revise → Edit → Proofread." },
{ id:"w5-09", week:5, topic:"Pre-writing & Post-writing", difficulty:"hard",
  question:"Why is the post-writing stage important?",
  options:["It generates the original ideas","It improves clarity, correctness, and overall quality of the final piece","It replaces the need for a topic","It happens before any draft exists"],
  correct:1,
  explanation:"Post-writing activities catch errors and weaknesses that pre-writing and drafting can't, polishing the final output.",
  memoryTip:"Post-writing = quality control before the final version." },

/* ---------------- WEEK 6: Types of Writing ---------------- */
{ id:"w6-01", week:6, topic:"Types of Writing", difficulty:"easy",
  question:"Descriptive writing aims to:",
  options:["Convince the reader of a viewpoint","Create a vivid picture of a person, place, or thing using sensory detail","Explain a process step-by-step","Tell a chronological story"],
  correct:1,
  explanation:"Descriptive writing appeals to the senses (sight, sound, smell, touch, taste) to paint a vivid picture for the reader.",
  memoryTip:"Descriptive = DESCRIBE using the five senses." },
{ id:"w6-02", week:6, topic:"Types of Writing", difficulty:"easy",
  question:"Narrative writing primarily:",
  options:["Explains a scientific process","Tells a story with a sequence of events","Argues for a particular opinion","Lists facts without a storyline"],
  correct:1,
  explanation:"Narrative writing tells a story, typically involving characters, setting, conflict, and a sequence of events.",
  memoryTip:"Narrative = tells a NARRATIVE (a story)." },
{ id:"w6-03", week:6, topic:"Types of Writing", difficulty:"easy",
  question:"Expository writing is primarily used to:",
  options:["Persuade the reader emotionally","Explain or inform about a topic using facts","Describe a scene using sensory language","Narrate a personal experience"],
  correct:1,
  explanation:"Expository writing informs or explains a topic clearly and objectively, often using facts, definitions, and examples.",
  memoryTip:"Expository = EXPOSES/explains the facts." },
{ id:"w6-04", week:6, topic:"Types of Writing", difficulty:"medium",
  question:"Argumentative (persuasive) writing aims to:",
  options:["Simply describe a scene","Convince the reader to accept a viewpoint or take action","Narrate a sequence of past events","List instructions in order"],
  correct:1,
  explanation:"Argumentative writing uses evidence and reasoning to persuade the reader toward a particular position or action.",
  memoryTip:"Argumentative = builds an ARGUMENT to persuade." },
{ id:"w6-05", week:6, topic:"Types of Writing", difficulty:"medium",
  question:"Which type of writing relies most heavily on evidence and logical reasoning?",
  options:["Descriptive writing","Argumentative writing","Purely narrative writing","None of these use evidence"],
  correct:1,
  explanation:"Argumentative writing depends on structured evidence and logical reasoning to support and defend its claims.",
  memoryTip:"Argumentative = evidence-driven persuasion." },
{ id:"w6-06", week:6, topic:"Types of Writing", difficulty:"medium",
  question:"A narrative essay typically follows:",
  options:["A list of unordered facts","A chronological structure with characters and plot","A strictly persuasive structure","No structure at all"],
  correct:1,
  explanation:"Narrative essays are usually organized chronologically, following characters and events through a plot.",
  memoryTip:"Narrative = beginning, middle, end (a plot)." },
{ id:"w6-07", week:6, topic:"Types of Writing", difficulty:"medium",
  question:"Which type of writing would best suit a 'how-to' guide?",
  options:["Descriptive writing","Expository writing","Purely persuasive writing","Purely narrative writing"],
  correct:1,
  explanation:"'How-to' guides explain a process step by step, which is a core function of expository writing.",
  memoryTip:"Instructions = explaining = expository." },
{ id:"w6-08", week:6, topic:"Types of Writing", difficulty:"hard",
  question:"Persuasive writing differs from argumentative writing mainly in that persuasive writing:",
  options:["Never uses evidence","Appeals more to emotion, while argumentative relies more on logic and evidence","Is always shorter","Has no clear position"],
  correct:1,
  explanation:"Both aim to convince, but persuasive writing leans more on emotional appeal, while argumentative writing leans more on structured logical evidence.",
  memoryTip:"Persuasive = heart (emotion); Argumentative = head (logic)." },
{ id:"w6-09", week:6, topic:"Types of Writing", difficulty:"hard",
  question:"Which writing type would best explain the causes of climate change with facts?",
  options:["Narrative writing","Expository writing","Descriptive writing only","Purely persuasive writing"],
  correct:1,
  explanation:"Explaining causes and effects with factual, informative detail is a hallmark of expository writing.",
  memoryTip:"Explaining 'why/how' with facts = expository." },
{ id:"w6-10", week:6, topic:"Types of Writing", difficulty:"medium",
  question:"Descriptive writing often relies heavily on:",
  options:["Statistics and data","Sensory language (sight, sound, smell, touch, taste)","Logical syllogisms","Step-by-step instructions"],
  correct:1,
  explanation:"Descriptive writing uses vivid, sensory-rich language to help readers visualize and experience what's being described.",
  memoryTip:"Descriptive = paint with the FIVE SENSES." },

/* ---------------- WEEK 7: SQ3R / Reading Strategies ---------------- */
{ id:"w7-01", week:7, topic:"SQ3R & Reading Strategies", difficulty:"easy",
  question:"SQ3R stands for:",
  options:["Survey, Question, Read, Recite, Review","Skim, Quote, Read, Repeat, Recall","Study, Quiz, Rehearse, Record, Report","Scan, Question, Reread, Recite, Rest"],
  correct:0,
  explanation:"SQ3R is a five-step reading comprehension method: Survey, Question, Read, Recite, Review.",
  memoryTip:"SQ3R = Survey, Question, Read, Recite, Review (the '3R's)." },
{ id:"w7-02", week:7, topic:"SQ3R & Reading Strategies", difficulty:"medium",
  question:"The 'Survey' step in SQ3R involves:",
  options:["Reading every word carefully first","Skimming the text to get an overview before detailed reading","Writing a full summary","Testing your memory of the text"],
  correct:1,
  explanation:"Surveying means quickly skimming headings, subheadings, and summaries to get a general sense of the text before reading in depth.",
  memoryTip:"Survey = a quick 'bird's-eye view' first." },
{ id:"w7-03", week:7, topic:"SQ3R & Reading Strategies", difficulty:"medium",
  question:"The 'Question' step in SQ3R involves:",
  options:["Answering a final exam","Turning headings/topics into questions to guide reading","Skipping the introduction","Ignoring the text structure"],
  correct:1,
  explanation:"Turning section headings into questions gives the reader a purpose and focus while reading.",
  memoryTip:"Turn 'Photosynthesis' (heading) into 'What is photosynthesis?' (question)." },
{ id:"w7-04", week:7, topic:"SQ3R & Reading Strategies", difficulty:"medium",
  question:"The 'Read' step in SQ3R involves:",
  options:["Reading passively without purpose","Reading actively to find answers to the questions formed earlier","Reading only the conclusion","Skipping difficult sections"],
  correct:1,
  explanation:"Active reading in SQ3R means reading with the specific goal of answering the questions generated in the previous step.",
  memoryTip:"Read = read WITH a purpose (answering your own questions)." },
{ id:"w7-05", week:7, topic:"SQ3R & Reading Strategies", difficulty:"medium",
  question:"The 'Recite' step in SQ3R involves:",
  options:["Rereading the text word for word","Summarizing what was read in your own words, often aloud","Highlighting every sentence","Skipping ahead to the next chapter"],
  correct:1,
  explanation:"Reciting means actively recalling and restating the material in your own words, which strengthens memory.",
  memoryTip:"Recite = say it back in YOUR own words." },
{ id:"w7-06", week:7, topic:"SQ3R & Reading Strategies", difficulty:"medium",
  question:"The 'Review' step in SQ3R involves:",
  options:["Ignoring the material after reading","Going back over the material to reinforce understanding and retention","Deleting your notes","Reading a completely different text"],
  correct:1,
  explanation:"Reviewing consolidates learning by revisiting notes and key points after the initial reading and recitation.",
  memoryTip:"Review = a final loop back to lock in memory." },
{ id:"w7-07", week:7, topic:"SQ3R & Reading Strategies", difficulty:"easy",
  question:"SQ3R is primarily a strategy for:",
  options:["Writing essays faster","Improving reading comprehension and retention","Memorizing vocabulary lists only","Public speaking practice"],
  correct:1,
  explanation:"SQ3R is a structured reading method designed to boost comprehension and long-term retention of written material.",
  memoryTip:"SQ3R = a reading comprehension toolkit." },
{ id:"w7-08", week:7, topic:"SQ3R & Reading Strategies", difficulty:"hard",
  question:"Skimming differs from scanning in that skimming:",
  options:["Looks for one specific fact","Gets a general overview of the whole text","Is slower than scanning","Requires reading every word"],
  correct:1,
  explanation:"Skimming gives a broad overview of the whole text, while scanning searches quickly for a specific piece of information.",
  memoryTip:"Skim = the whole picture. Scan = one specific detail." },
{ id:"w7-09", week:7, topic:"SQ3R & Reading Strategies", difficulty:"hard",
  question:"Why is the 'Recite' step considered important for retention?",
  options:["It wastes time better spent rereading","It reinforces memory by actively recalling information rather than passively rereading","It replaces the need to read the text at all","It only helps with spelling"],
  correct:1,
  explanation:"Active recall (reciting) is more effective for long-term retention than passive rereading, a well-established memory principle.",
  memoryTip:"Active recall > passive rereading, for memory." },

/* ---------------- WEEK 8: Word Formation & Vocabulary ---------------- */
{ id:"w8-01", week:8, topic:"Word Formation & Vocabulary", difficulty:"easy",
  question:"Affixation is a word formation process that:",
  options:["Combines two full words into one","Adds a prefix or suffix to a root word","Shortens a long word","Borrows a word from another language"],
  correct:1,
  explanation:"Affixation creates new words by attaching prefixes (un-, re-) or suffixes (-ness, -able) to a root word.",
  memoryTip:"Affixation = attach an AFFIX (prefix/suffix)." },
{ id:"w8-02", week:8, topic:"Word Formation & Vocabulary", difficulty:"medium",
  question:"Compounding involves:",
  options:["Removing letters from a word","Combining two or more whole words to form a new one (e.g. 'toothbrush')","Borrowing directly from another language","Creating an acronym"],
  correct:1,
  explanation:"Compounding joins two independent words together to create a new word with a new meaning, like 'tooth' + 'brush' = 'toothbrush'.",
  memoryTip:"Compound = two whole words glued together." },
{ id:"w8-03", week:8, topic:"Word Formation & Vocabulary", difficulty:"medium",
  question:"Blending involves:",
  options:["Combining parts of two words into one (e.g. 'smog' from smoke + fog)","Adding a prefix to a root word","Using the first letters of a phrase","Copying a word exactly from another language"],
  correct:0,
  explanation:"Blending fuses parts of two words together, as in 'smoke' + 'fog' = 'smog', or 'breakfast' + 'lunch' = 'brunch'.",
  memoryTip:"Blend = mix PARTS of two words, like a smoothie." },
{ id:"w8-04", week:8, topic:"Word Formation & Vocabulary", difficulty:"medium",
  question:"Clipping involves:",
  options:["Shortening a longer word (e.g. 'phone' from 'telephone')","Joining two full words together","Borrowing a foreign word","Reversing the order of syllables"],
  correct:0,
  explanation:"Clipping shortens an existing word by cutting off part of it while keeping the same meaning, e.g. 'ad' from 'advertisement'.",
  memoryTip:"Clipping = 'clip off' part of a longer word." },
{ id:"w8-05", week:8, topic:"Word Formation & Vocabulary", difficulty:"medium",
  question:"An acronym is formed by:",
  options:["Blending two unrelated words","Combining the initial letters of a phrase into a pronounceable word (e.g. 'NASA')","Removing an affix from a word","Borrowing directly from Latin"],
  correct:1,
  explanation:"Acronyms take the first letters of a multi-word phrase and form a new, pronounceable word, such as 'NASA' or 'radar'.",
  memoryTip:"Acronym = first letters that spell a NEW pronounceable word." },
{ id:"w8-06", week:8, topic:"Word Formation & Vocabulary", difficulty:"medium",
  question:"Borrowing as a word formation process means:",
  options:["Creating an entirely new word from nothing","Adopting a word from another language","Removing a suffix","Reversing a word's spelling"],
  correct:1,
  explanation:"Borrowing occurs when a language adopts a word from another language, e.g. English borrowing 'safari' from Swahili.",
  memoryTip:"Borrowing = 'lending' a word from another language." },
{ id:"w8-07", week:8, topic:"Word Formation & Vocabulary", difficulty:"hard",
  question:"Coinage refers to:",
  options:["The creation of an entirely new word, often for a new product or concept","Shortening an existing word","Joining two existing words","Using an acronym"],
  correct:0,
  explanation:"Coinage is inventing a brand-new word from scratch, often for new inventions or brands, e.g. 'Google' or 'Kleenex' becoming generic terms.",
  memoryTip:"Coinage = MINTING (coining) a brand-new word." },
{ id:"w8-08", week:8, topic:"Word Formation & Vocabulary", difficulty:"hard",
  question:"Conversion (functional shift) occurs when:",
  options:["A word changes its part of speech without changing its form (e.g. 'email' noun to verb)","Two words are combined","A word is shortened","A word is borrowed from another language"],
  correct:0,
  explanation:"Conversion shifts a word's grammatical category without altering its spelling, such as using the noun 'email' as a verb ('email me').",
  memoryTip:"Conversion = same spelling, new job (part of speech)." },
{ id:"w8-09", week:8, topic:"Word Formation & Vocabulary", difficulty:"hard",
  question:"Back-formation involves:",
  options:["Creating a new word by removing an (apparent) affix from an existing word (e.g. 'edit' from 'editor')","Joining two complete words","Borrowing a word from French","Using acronyms in speech"],
  correct:0,
  explanation:"Back-formation removes what looks like an affix from a longer word to create a shorter new word, e.g. 'edit' was formed by removing '-or' from 'editor'.",
  memoryTip:"Back-formation = working BACKWARDS by stripping an affix." },
{ id:"w8-10", week:8, topic:"Word Formation & Vocabulary", difficulty:"medium",
  question:"Understanding word formation processes primarily helps learners:",
  options:["Memorize spelling rules only","Deduce the meaning of unfamiliar words by recognizing their parts","Avoid using new vocabulary","Speak faster"],
  correct:1,
  explanation:"Recognizing prefixes, roots, and formation patterns helps learners guess the meaning of unfamiliar vocabulary encountered while reading.",
  memoryTip:"Know the parts, guess the whole word's meaning." },

/* ---------------- WEEK 9: Stress and Meaning ---------------- */
{ id:"w9-01", week:9, topic:"Stress and Meaning", difficulty:"easy",
  question:"Word stress refers to:",
  options:["The volume of an entire sentence","Emphasis placed on a particular syllable within a word","The speed of speech","The punctuation used in writing"],
  correct:1,
  explanation:"Word stress is the extra emphasis (loudness, pitch, length) given to one syllable within a multi-syllable word.",
  memoryTip:"Word stress = which SYLLable gets the punch." },
{ id:"w9-02", week:9, topic:"Stress and Meaning", difficulty:"easy",
  question:"Sentence stress refers to:",
  options:["Emphasis placed on certain words within a sentence to highlight meaning","The number of words in a sentence","The grammatical subject of a sentence","A type of punctuation"],
  correct:0,
  explanation:"Sentence stress highlights key content words in a sentence to draw attention to important meaning.",
  memoryTip:"Sentence stress = spotlighting the IMPORTANT words." },
{ id:"w9-03", week:9, topic:"Stress and Meaning", difficulty:"medium",
  question:"Changing the stress placement in certain English words can:",
  options:["Never affect meaning","Change the word's meaning or grammatical function (e.g. noun vs. verb)","Only affect spelling","Only happen in written English"],
  correct:1,
  explanation:"Some English words shift meaning or part of speech depending on stress, e.g. 'REcord' (noun) vs. 're-CORD' (verb).",
  memoryTip:"Stress can flip a word from noun to verb (and back)." },
{ id:"w9-04", week:9, topic:"Stress and Meaning", difficulty:"medium",
  question:"Which word pair best demonstrates stress shifting the part of speech?",
  options:["'Happy' and 'happily'","'PREsent' (noun) vs. 'preSENT' (verb)","'Cat' and 'cats'","'Book' and 'books'"],
  correct:1,
  explanation:"'PREsent' (a gift, stress on first syllable) and 'preSENT' (to give, stress on second syllable) show stress determining part of speech.",
  memoryTip:"PREsent (gift) vs. preSENT (to give) — stress flips the meaning." },
{ id:"w9-05", week:9, topic:"Stress and Meaning", difficulty:"medium",
  question:"In a sentence, content words are typically:",
  options:["Unstressed","Stressed","Removed entirely","Only used in writing"],
  correct:1,
  explanation:"Content words (nouns, main verbs, adjectives, adverbs) carry the core meaning and are typically stressed in speech.",
  memoryTip:"Content words carry meaning → they get the stress." },
{ id:"w9-06", week:9, topic:"Stress and Meaning", difficulty:"medium",
  question:"In a sentence, function words are typically:",
  options:["Stressed heavily","Unstressed","Removed from speech","Always capitalized"],
  correct:1,
  explanation:"Function words (articles, prepositions, auxiliary verbs) are usually spoken quickly and without stress since they carry grammatical, not lexical, weight.",
  memoryTip:"Function words = the 'quiet glue' in speech." },
{ id:"w9-07", week:9, topic:"Stress and Meaning", difficulty:"hard",
  question:"Intonation refers to:",
  options:["The rise and fall of pitch in speech","The spelling of a word","The number of syllables in a sentence","A punctuation rule"],
  correct:0,
  explanation:"Intonation is the melodic rise and fall of pitch across an utterance, which can convey attitude, emphasis, or sentence type.",
  memoryTip:"Intonation = the 'musical tune' of speech." },
{ id:"w9-08", week:9, topic:"Stress and Meaning", difficulty:"medium",
  question:"Rising intonation is commonly associated with:",
  options:["Commands","Yes/no questions","Statements of fact","Lists"],
  correct:1,
  explanation:"Yes/no questions in English typically end with rising intonation, e.g. 'Are you coming?' ↗",
  memoryTip:"Yes/no question? → voice goes UP at the end." },
{ id:"w9-09", week:9, topic:"Stress and Meaning", difficulty:"medium",
  question:"Falling intonation is commonly associated with:",
  options:["Yes/no questions","Statements and commands","Uncertain trailing thoughts","Nothing in particular"],
  correct:1,
  explanation:"Declarative statements and commands typically end with falling intonation, signaling completeness and certainty.",
  memoryTip:"Statement/command? → voice falls at the end." },
{ id:"w9-10", week:9, topic:"Stress and Meaning", difficulty:"hard",
  question:"When responding to a speaking prompt, a speaker should first:",
  options:["Start talking immediately without thinking","Understand and organize their thoughts around the prompt","Ignore the prompt's actual question","Speak as fast as possible"],
  correct:1,
  explanation:"Good spoken responses start with a moment to understand the prompt and mentally structure a coherent answer before speaking.",
  memoryTip:"Think first, then speak — organize before you open your mouth." },

/* ---------------- WEEK 10: Public Speaking & Arguments ---------------- */
{ id:"w10-01", week:10, topic:"Public Speaking & Arguments", difficulty:"easy",
  question:"A key element of effective public speaking is:",
  options:["Speaking as quietly as possible","Clear organization and audience awareness","Avoiding eye contact","Using only technical jargon"],
  correct:1,
  explanation:"Effective speeches are clearly organized and tailored to the audience's needs, knowledge, and interests.",
  memoryTip:"Good speaking = clear structure + know your audience." },
{ id:"w10-02", week:10, topic:"Public Speaking & Arguments", difficulty:"medium",
  question:"Deductive reasoning moves from:",
  options:["Specific observations to a general conclusion","General premises to a specific conclusion","No premises at all","Random guesses to a certain answer"],
  correct:1,
  explanation:"Deductive reasoning starts with general premises and applies them logically to reach a specific, certain conclusion.",
  memoryTip:"Deductive = 'De-duce' DOWN from general to specific." },
{ id:"w10-03", week:10, topic:"Public Speaking & Arguments", difficulty:"medium",
  question:"Inductive reasoning moves from:",
  options:["General premises to a specific conclusion","Specific observations to a general conclusion","A conclusion to a premise","Nowhere — it has no direction"],
  correct:1,
  explanation:"Inductive reasoning builds a general conclusion from a pattern of specific observations or evidence.",
  memoryTip:"Inductive = 'IN-duce' UP from specific cases to a general rule." },
{ id:"w10-04", week:10, topic:"Public Speaking & Arguments", difficulty:"medium",
  question:"Which is an example of deductive reasoning?",
  options:["The sun has risen every day I've observed, so it will rise tomorrow","All men are mortal; Socrates is a man; therefore Socrates is mortal","Most swans I've seen are white, so all swans are probably white","I feel tired, so I must be sick"],
  correct:1,
  explanation:"This is the classic deductive syllogism: two general premises logically guarantee a specific, certain conclusion.",
  memoryTip:"Classic deduction: General rule + specific case = certain conclusion." },
{ id:"w10-05", week:10, topic:"Public Speaking & Arguments", difficulty:"medium",
  question:"Which is an example of inductive reasoning?",
  options:["All men are mortal; Socrates is a man; therefore Socrates is mortal","The sun has risen every day observed, so it will likely rise tomorrow","2 + 2 = 4, therefore all math is true","If it rains, the ground gets wet; the ground is wet, so it rained (a formal fallacy, but illustrates a different point)"],
  correct:1,
  explanation:"This reasons from repeated specific observations (sunrise every day) to a general/probable conclusion (it will rise again) — the hallmark of induction.",
  memoryTip:"Repeated pattern observed → probable general conclusion = induction." },
{ id:"w10-06", week:10, topic:"Public Speaking & Arguments", difficulty:"hard",
  question:"A valid deductive argument with true premises guarantees:",
  options:["A probable conclusion only","A true conclusion","No conclusion at all","A false conclusion"],
  correct:1,
  explanation:"If a deductive argument is logically valid and its premises are true, the conclusion is guaranteed to be true.",
  memoryTip:"Valid deduction + true premises = certain truth." },
{ id:"w10-07", week:10, topic:"Public Speaking & Arguments", difficulty:"hard",
  question:"Inductive arguments provide conclusions that are:",
  options:["Always 100% certain","Probable, not certain","Always false","Irrelevant to evidence"],
  correct:1,
  explanation:"Because inductive reasoning generalizes from limited observations, its conclusions are probable but never fully guaranteed.",
  memoryTip:"Induction gives PROBABILITY, not certainty." },
{ id:"w10-08", week:10, topic:"Public Speaking & Arguments", difficulty:"easy",
  question:"Effective speeches typically follow a structure of:",
  options:["Conclusion, body, introduction","Introduction, body, and conclusion","Random order of ideas","Only a body, no framing"],
  correct:1,
  explanation:"A clear introduction (hook + preview), body (main points), and conclusion (summary + close) is the standard effective speech structure.",
  memoryTip:"Tell them what you'll say, say it, tell them what you said." },
{ id:"w10-09", week:10, topic:"Public Speaking & Arguments", difficulty:"medium",
  question:"Eye contact and vocal variety in public speaking primarily help to:",
  options:["Confuse the audience","Engage and persuade the audience","Shorten the speech","Replace the need for content"],
  correct:1,
  explanation:"Non-verbal delivery elements like eye contact and vocal variety keep the audience engaged and reinforce the speaker's credibility and persuasiveness.",
  memoryTip:"Delivery skills = engagement + persuasion boosters." },
{ id:"w10-10", week:10, topic:"Public Speaking & Arguments", difficulty:"hard",
  question:"A rhetorical question in a speech is used to:",
  options:["Demand an immediate literal answer from the audience","Engage the audience or emphasize a point without expecting a literal answer","Confuse the listener intentionally","End the speech abruptly"],
  correct:1,
  explanation:"Rhetorical questions are asked for effect — to provoke thought or emphasize a point — not to receive a literal spoken answer.",
  memoryTip:"Rhetorical question = a question that answers itself." },

/* ---------------- WEEK 11: Listening Skills ---------------- */
{ id:"w11-01", week:11, topic:"Listening Skills", difficulty:"easy",
  question:"Active listening involves:",
  options:["Simply hearing sounds passively","Fully concentrating on, understanding, and responding to a speaker","Interrupting frequently to share opinions","Multitasking while a speaker talks"],
  correct:1,
  explanation:"Active listening requires full attention, genuine understanding, and appropriate feedback to the speaker.",
  memoryTip:"Active listening = ears AND mind fully engaged." },
{ id:"w11-02", week:11, topic:"Listening Skills", difficulty:"medium",
  question:"Passive listening differs from active listening because it:",
  options:["Involves more feedback","Lacks full engagement or feedback from the listener","Requires eye contact","Is always more effective"],
  correct:1,
  explanation:"Passive listening happens with minimal engagement — hearing without truly processing or responding to the message.",
  memoryTip:"Passive listening = present in body, absent in mind." },
{ id:"w11-03", week:11, topic:"Listening Skills", difficulty:"medium",
  question:"A common barrier to effective listening is:",
  options:["Maintaining eye contact","Distraction or prejudgment of the speaker","Asking clarifying questions","Taking notes"],
  correct:1,
  explanation:"Distractions and forming judgments before the speaker finishes are common obstacles that prevent effective listening.",
  memoryTip:"Barriers to listening: distraction and premature judgment." },
{ id:"w11-04", week:11, topic:"Listening Skills", difficulty:"medium",
  question:"Listening for 'gist' means:",
  options:["Focusing on every single word","Listening for the general idea rather than every detail","Ignoring the speaker entirely","Repeating the message verbatim"],
  correct:1,
  explanation:"Listening for gist means grasping the overall meaning or main point without needing every specific detail.",
  memoryTip:"Gist = the 'big picture' takeaway." },
{ id:"w11-05", week:11, topic:"Listening Skills", difficulty:"medium",
  question:"Listening for specific information means:",
  options:["Focusing on particular details such as names, dates, or figures","Ignoring the overall topic","Listening only to the introduction","Summarizing the whole speech"],
  correct:0,
  explanation:"This type of listening zooms in on precise details rather than the general meaning — useful for finding exact facts.",
  memoryTip:"Specific listening = hunting for exact details." },
{ id:"w11-06", week:11, topic:"Listening Skills", difficulty:"hard",
  question:"Why is listening considered a critical communication skill?",
  options:["It has no real impact on communication outcomes","It enables accurate understanding and appropriate response","It replaces the need for speaking","It only matters in formal settings"],
  correct:1,
  explanation:"Without effective listening, messages are misunderstood, making appropriate responses and successful communication difficult.",
  memoryTip:"No good listening = no good communication." },
{ id:"w11-07", week:11, topic:"Listening Skills", difficulty:"medium",
  question:"Which behavior best demonstrates active listening?",
  options:["Interrupting to change the subject","Maintaining eye contact and asking clarifying questions","Checking a phone while someone talks","Planning your reply while the person is still speaking"],
  correct:1,
  explanation:"Eye contact and clarifying questions show genuine engagement and effort to understand the speaker fully.",
  memoryTip:"Active listener signs: eye contact + good questions." },
{ id:"w11-08", week:11, topic:"Listening Skills", difficulty:"hard",
  question:"Selective listening can lead to:",
  options:["Perfect understanding of every message","Missing important parts of a message","Improved memory of the whole conversation","No negative consequences"],
  correct:1,
  explanation:"Selective listening — tuning in only to parts that interest you — risks missing important information in the rest of the message.",
  memoryTip:"Selective listening = cherry-picking, and missing the rest." },
{ id:"w11-09", week:11, topic:"Listening Skills", difficulty:"medium",
  question:"Effective listeners typically avoid:",
  options:["Asking questions","Interrupting the speaker","Making eye contact","Taking notes"],
  correct:1,
  explanation:"Interrupting disrupts the speaker's message and signals a lack of full attention — something effective listeners avoid.",
  memoryTip:"Good listeners let the speaker finish." },
{ id:"w11-10", week:11, topic:"Listening Skills", difficulty:"hard",
  question:"Empathetic listening focuses on:",
  options:["Correcting the speaker's grammar","Understanding the speaker's feelings and perspective","Finding logical flaws in the argument","Timing how long the speaker talks"],
  correct:1,
  explanation:"Empathetic listening prioritizes emotionally understanding and validating the speaker's perspective, rather than judging or analyzing.",
  memoryTip:"Empathetic = listening with the HEART, not just the ears." },

/* ---------------- WEEK 12: Critical Reasoning & Note-Taking ---------------- */
{ id:"w12-01", week:12, topic:"Critical Reasoning & Note-Taking", difficulty:"medium",
  question:"Critical listening involves:",
  options:["Simply understanding a message","Evaluating and analyzing the speaker's message, not just understanding it","Ignoring the speaker's evidence","Repeating the message word for word"],
  correct:1,
  explanation:"Critical listening goes beyond comprehension to actively assess the validity, bias, and quality of what's being said.",
  memoryTip:"Critical listening = listen AND judge/evaluate." },
{ id:"w12-02", week:12, topic:"Critical Reasoning & Note-Taking", difficulty:"medium",
  question:"The Cornell note-taking method divides the page into:",
  options:["One single undivided section","Cue column, notes column, and a summary section","Only a title and date","Four equal quadrants"],
  correct:1,
  explanation:"The Cornell method splits the page into a narrow cue/question column, a wider notes column, and a summary section at the bottom.",
  memoryTip:"Cornell = Cues + Notes + Summary (3 zones)." },
{ id:"w12-03", week:12, topic:"Critical Reasoning & Note-Taking", difficulty:"medium",
  question:"The outline method of note-taking organizes information using:",
  options:["Random scattered notes","Headings and indented sub-points showing hierarchy","Only pictures and diagrams","A single paragraph with no structure"],
  correct:1,
  explanation:"The outline method uses indentation to show the hierarchical relationship between main points and supporting details.",
  memoryTip:"Outline = main points, with sub-points INDENTED underneath." },
{ id:"w12-04", week:12, topic:"Critical Reasoning & Note-Taking", difficulty:"medium",
  question:"Mind mapping as a note-taking method is especially useful for:",
  options:["Recording verbatim transcripts","Visually representing relationships between ideas","Avoiding the need to review notes later","Only listing numbers and dates"],
  correct:1,
  explanation:"Mind maps use branching diagrams from a central idea to visually show how concepts relate to one another.",
  memoryTip:"Mind map = a visual WEB of connected ideas." },
{ id:"w12-05", week:12, topic:"Critical Reasoning & Note-Taking", difficulty:"medium",
  question:"Active note-taking during a presentation primarily helps:",
  options:["Distract from the speaker","Improve retention and organization of information","Replace the need to listen","Slow down the speaker"],
  correct:1,
  explanation:"Taking notes actively engages the brain with the material, improving both understanding in the moment and later recall.",
  memoryTip:"Note-taking = an active memory booster, not a passive record." },
{ id:"w12-06", week:12, topic:"Critical Reasoning & Note-Taking", difficulty:"hard",
  question:"Logical reasoning strengthens a presentation's argument by:",
  options:["Making it longer","Ensuring conclusions follow validly from the evidence presented","Adding more emotional appeals only","Avoiding the use of any evidence"],
  correct:1,
  explanation:"Sound logical reasoning ensures that the conclusions drawn genuinely follow from the evidence and premises given, making the argument credible.",
  memoryTip:"Logic = the evidence actually SUPPORTS the conclusion." },
{ id:"w12-07", week:12, topic:"Critical Reasoning & Note-Taking", difficulty:"hard",
  question:"A fallacy in reasoning is best defined as:",
  options:["A strong, well-supported argument","An error in logic that weakens an argument","A type of punctuation mark","A note-taking method"],
  correct:1,
  explanation:"A logical fallacy is a flaw in reasoning — such as a false cause or hasty generalization — that undermines the validity of an argument.",
  memoryTip:"Fallacy = a FLAW hiding inside the logic." },
{ id:"w12-08", week:12, topic:"Critical Reasoning & Note-Taking", difficulty:"medium",
  question:"Critical thinking involves:",
  options:["Accepting all information without question","Objectively analyzing and evaluating information before accepting it","Ignoring evidence that contradicts your opinion","Memorizing facts without understanding them"],
  correct:1,
  explanation:"Critical thinking requires actively questioning, analyzing, and evaluating claims and evidence rather than accepting them at face value.",
  memoryTip:"Critical thinking = question first, accept later (if justified)." },
{ id:"w12-09", week:12, topic:"Critical Reasoning & Note-Taking", difficulty:"medium",
  question:"Effective note-taking should prioritize:",
  options:["Writing down every single word said","Key points and main ideas over verbatim transcription","Only writing down the speaker's jokes","Skipping the introduction entirely"],
  correct:1,
  explanation:"Good notes capture essential points and structure rather than attempting a word-for-word transcript, which is inefficient and less useful for review.",
  memoryTip:"Notes = capture the MAIN IDEAS, not every word." },
{ id:"w12-10", week:12, topic:"Critical Reasoning & Note-Taking", difficulty:"hard",
  question:"Reviewing notes soon after a lecture primarily helps:",
  options:["Erase the material from memory faster","Reinforce memory and retention of the material","Replace the need to ever study again","Confuse the original understanding"],
  correct:1,
  explanation:"Reviewing notes shortly after learning combats the natural 'forgetting curve,' reinforcing memory before it fades.",
  memoryTip:"Review SOON — beat the forgetting curve early." }

];

if (typeof module !== "undefined" && module.exports) { module.exports = QUESTIONS; }
